/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.scraper;

import okhttp3.*;
import org.jsoup.Connection;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

import java.io.*;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.logging.LogManager;
import java.util.logging.Logger;

public class App {
    static Logger logger = Logger.getLogger(App.class.getName());
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
                "(KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36";
        try {

            Connection.Response res = Jsoup.connect("https://www.screener.in/login/?")
                    .method(Connection.Method.GET)
                    .execute();

            Map<String, String> loginCookies = res.cookies();
            logger.info(loginCookies.toString());

            res = Jsoup.connect("https://www.screener.in/login")
                    .cookie("cookie", "csrftoken=CPfQQygNgiXgiBoyd4gEcjxsLnGkg5Cl")
                    .header("user-agent", userAgent)
                    .header("origin", "https://www.screener.in")
                    .header("content-type", "application/x-www-form-urlencoded")
//                    .header("Content-Length", "145")
//                    .header("Host", "www.screener.in")
                    .data("username", "testaccount@yopmail.com", "password", "143@Siri", "csrfmiddlewaretoken",
                            "UVMKZzf6nPSImEkbaNf7KZVE11sGqW4xmARqFXlJtXFOu5yzdHlBM8iWCeYQwRwI", "next", "")
                    .method(Connection.Method.POST)
                    .followRedirects(true)
                    .timeout(0)
                    .execute();
            loginCookies = res.cookies();

            logger.info(loginCookies.toString());
            logger.info(res.body());
            logger.info(res.headers().toString());

            Document doc = Jsoup.connect("https://www.screener.in/company/HDFCBANK/consolidated/")
                    .referrer("https://www.screener.in/dash")
                    .cookies(loginCookies)
                    .get();

            BufferedWriter writer = new BufferedWriter(new FileWriter("/Users/mac/Desktop/test.html"));
            writer.write(doc.html());
            writer.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void sendMessage(BufferedWriter out, File request) throws IOException {
        System.out.println(" * Request");

        for (String line : getContents(request)) {
            System.out.println(line);
            out.write(line + "\r\n");
        }

        out.write("\r\n");
        out.flush();
    }

    private static void readResponse(BufferedReader in) throws IOException {
        System.out.println("\n * Response");

        String line;
        while ((line = in.readLine()) != null) {
            System.out.println(line);
        }
    }

    private static List<String> getContents(File file) throws IOException {
        List<String> contents = new ArrayList<String>();

        BufferedReader input = new BufferedReader(new FileReader(file));
        String line;
        while ((line = input.readLine()) != null) {
            contents.add(line);
        }
        input.close();

        return contents;
    }
}
